// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLunarData() {
  return window['go']['zhanbu']['App']['FetchLunarData']();
}

export function GetAppVersion() {
  return window['go']['zhanbu']['App']['GetAppVersion']();
}

export function GetDefaultSavePath() {
  return window['go']['zhanbu']['App']['GetDefaultSavePath']();
}

export function GetDivinationRecords() {
  return window['go']['zhanbu']['App']['GetDivinationRecords']();
}

export function GetMeihuaRecords() {
  return window['go']['zhanbu']['App']['GetMeihuaRecords']();
}

export function Greet(arg1) {
  return window['go']['zhanbu']['App']['Greet'](arg1);
}

export function SaveDivinationRecord(arg1) {
  return window['go']['zhanbu']['App']['SaveDivinationRecord'](arg1);
}

export function SaveMeihuaRecord(arg1) {
  return window['go']['zhanbu']['App']['SaveMeihuaRecord'](arg1);
}

export function SaveScreenshot(arg1, arg2) {
  return window['go']['zhanbu']['App']['SaveScreenshot'](arg1, arg2);
}
