// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLunarData() {
  return window['go']['main']['App']['FetchLunarData']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveScreenshot(arg1, arg2) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2);
}
